version: "3.7"

services:
  postgres:
    image: postgres:12.3-alpine
    container_name: resort-db
    restart: always
    environment:
      - POSTGRES_DB=resort
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5433:5432
    volumes:
      - nft-db:/var/lib/postgresql/data/

volumes:
  nft-db:
